IMPORT ESSENCIAL LIBRARIES

In [103]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score

In [104]:
medical_df = pd.read_csv('insurance.csv')

In [105]:
medical_df.head()

,age,sex,bmi,children,smoker,region,charges
0,19,female,27.900,0,yes,southwest,16884.92400
1,18,male,33.770,1,no,southeast,1725.55230
2,28,male,33.000,3,no,southeast,4449.46200
3,33,male,22.705,0,no,northwest,21984.47061
4,32,male,28.880,0,no,northwest,3866.85520


EXPLORING AND ANALYZING DATA

In [106]:
 medical_df.shape

(1338, 7)

In [107]:
medical_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   age       1338 non-null   int64  
 1   sex       1338 non-null   object 
 2   bmi       1338 non-null   float64
 3   children  1338 non-null   int64  
 4   smoker    1338 non-null   object 
 5   region    1338 non-null   object 
 6   charges   1338 non-null   float64
dtypes: float64(2), int64(2), object(3)
memory usage: 73.3+ KB


In [108]:
medical_df.describe()

,age,bmi,children,charges
count,1338.000000,1338.000000,1338.000000,1338.000000
mean,39.207025,30.663397,1.094918,13270.422265
std,14.049960,6.098187,1.205493,12110.011237
min,18.000000,15.960000,0.000000,1121.873900
25%,27.000000,26.296250,0.000000,4740.287150
50%,39.000000,30.400000,1.000000,9382.033000
75%,51.000000,34.693750,2.000000,16639.912515
max,64.000000,53.130000,5.000000,63770.428010


In [109]:
medical_df.isnull().sum()

age         0
sex         0
bmi         0
children    0
smoker      0
region      0
charges     0
dtype: int64

In [110]:
medical_df.replace({'sex':{'male':0,'female':1}},inplace=True)
medical_df.replace({'smoker':{'yes':0,'no':1}},inplace=True)
medical_df.replace({'region':{'southeast':0,'southwest':1, 'northwest':2, 'northeast':3}},inplace=True)

C:\Users\MONISALI\AppData\Local\Temp\ipykernel_20604\3942459491.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  medical_df.replace({'sex':{'male':0,'female':1}},inplace=True)
C:\Users\MONISALI\AppData\Local\Temp\ipykernel_20604\3942459491.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  medical_df.replace({'smoker':{'yes':0,'no':1}},inplace=True)
C:\Users\MONISALI\AppData\Local\Temp\ipykernel_20604\3942459491.py:3: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To ret

DATA VISUALIZATION

In [111]:
# plt.figure(figsize=(3,3))
# sns.displot(data=medical_df, x='age')

In [112]:
# plt.figure(figsize=(3,3))
# sns.displot(data=medical_df, x='sex')

In [113]:
# plt.figure(figsize=(3,3))
# sns.displot(data=medical_df, x='bmi')

In [114]:
# plt.figure(figsize=(3,3))
# sns.displot(data=medical_df, x='children')

CONVERT CATEGORICAL COLUMN TO NUMERCIAL COLUMN

In [115]:
medical_df.head()

,age,sex,bmi,children,smoker,region,charges
0,19,1,27.900,0,0,1,16884.92400
1,18,0,33.770,1,1,0,1725.55230
2,28,0,33.000,3,1,0,4449.46200
3,33,0,22.705,0,1,2,21984.47061
4,32,0,28.880,0,1,2,3866.85520


TRAIN TEST SPLIT

In [116]:
X=medical_df.drop('charges',axis=1)
y= medical_df['charges']

In [117]:
 X_train, X_test, y_train, y_test = train_test_split(
...     X, y, test_size=0.1, random_state=2)

In [118]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
scaler.fit_transform(X_train)

array([[-0.16654954,  1.02013625, -0.48406661,  1.55535303,  0.51578654,
         0.47332575],
       [-0.3824006 ,  1.02013625,  0.42534842, -0.09673788,  0.51578654,
         1.35823912],
       [-0.81410274, -0.98026122,  1.21922978, -0.92278333,  0.51578654,
        -1.29650098],
       ...,
       [ 1.560259  , -0.98026122,  2.10058664, -0.92278333,  0.51578654,
        -0.41158761],
       [ 0.84075544,  1.02013625, -0.80425993, -0.09673788,  0.51578654,
        -0.41158761],
       [ 1.34440793,  1.02013625,  0.28423229, -0.09673788,  0.51578654,
         1.35823912]])

In [119]:
lg= LinearRegression()
lg.fit(X_train,y_train)
y_pred = lg.predict(X_test)

In [120]:
X_train= scaler.transform(X_train)
X_test = scaler.transform(X_test)
X_train

array([[-0.16654954,  1.02013625, -0.48406661,  1.55535303,  0.51578654,
         0.47332575],
       [-0.3824006 ,  1.02013625,  0.42534842, -0.09673788,  0.51578654,
         1.35823912],
       [-0.81410274, -0.98026122,  1.21922978, -0.92278333,  0.51578654,
        -1.29650098],
       ...,
       [ 1.560259  , -0.98026122,  2.10058664, -0.92278333,  0.51578654,
        -0.41158761],
       [ 0.84075544,  1.02013625, -0.80425993, -0.09673788,  0.51578654,
        -0.41158761],
       [ 1.34440793,  1.02013625,  0.28423229, -0.09673788,  0.51578654,
         1.35823912]])

In [121]:
r2_score(y_test,y_pred)

0.7058997983752826

In [122]:
medical_df.head()

,age,sex,bmi,children,smoker,region,charges
0,19,1,27.900,0,0,1,16884.92400
1,18,0,33.770,1,1,0,1725.55230
2,28,0,33.000,3,1,0,4449.46200
3,33,0,22.705,0,1,2,21984.47061
4,32,0,28.880,0,1,2,3866.85520


PREDICTION SYSTEM

In [123]:
input_df=(19,1,27.900,0,0,1)
np_df= np.asarray(input_df)
np_df_reshaped= np_df.reshape(1,-1)
prediction= lg.predict(np_df_reshaped)
print("Medical Insurance Charges are: ", prediction)

Medical Insurance Charges are:  [25925.06977975]


C:\Users\MONISALI\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([32.  ,  0.  , 28.88,  0.  ,  1.  ,  2.  ])

array([[32.  ,  0.  , 28.88,  0.  ,  1.  ,  2.  ]])

Medical Insurance Charges are:  [5459.71569296]


C:\Users\MONISALI\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


In [124]:
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.linear_model import Ridge
from sklearn.linear_model import Lasso

In [128]:
X_train, X_test, y_train, y_test = train_test_split(
...     X, y, test_size=0.1, random_state=2)
models= {'LinearRegression':LinearRegression(), 'DecisionTreeRegressor': DecisionTreeRegressor(),'RandomForestRegressor': RandomForestRegressor() }
result={}
for name,model in models.items():
    model.fit(X_train, y_train)
    y_pred= model.predict(X_test)
    score= r2_score(y_test,y_pred)
    result[name]= score
result
    

{'LinearRegression': 0.7058997983752826,
 'DecisionTreeRegressor': 0.6596980887651909,
 'RandomForestRegressor': 0.7443029368873837}

In [131]:
rfr=RandomForestRegressor()

In [132]:
rfr.fit(X_train, y_train)
y_pred= rfr.predict(X_test)
score= r2_score(y_test,y_pred)
score

0.7428241896114698

In [134]:
input_df1=(19,1,27.900,0,0,1)
np_df1 = np.asarray(input_df1)
np_df1_reshaped = np_df1.reshape(1,-1)
prediction=rfr.predict(np_df1_reshaped)
prediction

C:\Users\MONISALI\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(


array([16912.845482])